"""add ama agni roga columns

Revision ID: 856444844459
Revises: c7505004ed14
Create Date: 2026-02-06 23:21:28.984362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856444844459'
down_revision: Union[str, Sequence[str], None] = 'c7505004ed14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('ama', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('agni', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('roga', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'roga')
    op.drop_column('patients', 'agni')
    op.drop_column('patients', 'ama')
    # ### end Alembic commands ###
