"""add phone to patients

Revision ID: c7505004ed14
Revises: 1d0dd8dee60d
Create Date: 2026-01-29 20:36:19.031531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7505004ed14'
down_revision: Union[str, Sequence[str], None] = '1d0dd8dee60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

def upgrade():
    # Get database connection
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # Get all columns in 'patients' table
    columns = [c['name'] for c in inspector.get_columns('patients')]

    # Only add 'phone' if it is NOT in the list
    if 'phone' not in columns:
        op.add_column('patients', sa.Column('phone', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'phone')
    # ### end Alembic commands ###
