"""create patients and meal_plans

Revision ID: d4558d57405f
Revises: 
Create Date: 2026-01-27 14:40:48.543520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4558d57405f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_column('patients', 'vikriti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('vikriti', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
